name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Explain why this job ran
        run: echo ${{ github.event_name }} ${{ github.ref }} event triggered this step.
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hannesa2/android-ndk
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # ${{ steps.meta.outputs.labels }} comes with "***/android-ndk:api30-java11-NDK21
      # so we need it without ***
      - name: Find Tag
        if: startsWith(github.ref, 'refs/tags/')
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          commit-ish: HEAD
      - name: Create Github release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          hub release create -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.tagger.outputs.tag}}
